[
	{
		id: 1,
		attributes: {
			name: "Miód Wielokwiatowy",
			content:
				"Miody wielokwiatowe to duża grupa miodów, która jest jednym z popularniejszych i powszechnie stosowanych produktów pszczelich. Różnią się smakiem, barwą i walorami zdrowotnymi. Właściwości te są uzależnione od gatunków kwiatów, krzewów i drzew wybieranych przez pszczoły, miejsc występowania pasiek oraz terminów zbioru.",
			meta_description: "Miód wielokwiatowy od firmy Miodobranie",
			meta_title: "Miód wielokwiatowy - MIODOBRANIE",
			price: 40,
			slug: "miod-wielokwiatowy",
			createdAt: "2023-04-10T19:11:37.914Z",
			updatedAt: "2023-04-10T19:16:24.187Z",
			publishedAt: "2023-04-10T19:16:24.179Z",
			image: {
				data: {
					id: 1,
					attributes: {
						name: "pngwing(10).png",
						alternativeText: null,
						caption: null,
						width: 2362,
						height: 2362,
						formats: {
							thumbnail: {
								name: "thumbnail_pngwing(10).png",
								hash: "thumbnail_pngwing_10_eb7f6a5181",
								ext: ".png",
								mime: "image/png",
								path: null,
								width: 156,
								height: 156,
								size: 37.19,
								url: "/uploads/thumbnail_pngwing_10_eb7f6a5181.png",
							},
							small: {
								name: "small_pngwing(10).png",
								hash: "small_pngwing_10_eb7f6a5181",
								ext: ".png",
								mime: "image/png",
								path: null,
								width: 500,
								height: 500,
								size: 289.13,
								url: "/uploads/small_pngwing_10_eb7f6a5181.png",
							},
							medium: {
								name: "medium_pngwing(10).png",
								hash: "medium_pngwing_10_eb7f6a5181",
								ext: ".png",
								mime: "image/png",
								path: null,
								width: 750,
								height: 750,
								size: 611.17,
								url: "/uploads/medium_pngwing_10_eb7f6a5181.png",
							},
							large: {
								name: "large_pngwing(10).png",
								hash: "large_pngwing_10_eb7f6a5181",
								ext: ".png",
								mime: "image/png",
								path: null,
								width: 1000,
								height: 1000,
								size: 1048.6,
								url: "/uploads/large_pngwing_10_eb7f6a5181.png",
							},
						},
						hash: "pngwing_10_eb7f6a5181",
						ext: ".png",
						mime: "image/png",
						size: 1151.58,
						url: "/uploads/pngwing_10_eb7f6a5181.png",
						previewUrl: null,
						provider: "local",
						provider_metadata: null,
						createdAt: "2023-04-10T19:05:54.638Z",
						updatedAt: "2023-04-10T19:05:54.638Z",
					},
				},
			},
		},
		quantity: 2,
	},
];
